### ISSUE TITLE
Display bug when pon with akadora

### ISSUE THREAD

**Issue by nyantlet** [Equim-chan/akochan-reviewer#13]
![a](https://user-images.githubusercontent.com/69423443/95558573-68b12280-0a51-11eb-9950-4c99e7646a57.png)

akochan-reviewer version: [v0.4.4 (5811e5f)](https://github.com/Equim-chan/akochan-reviewer/releases/tag/v0.4.4)
Replay: https://tenhou.net/0/?log=2020100914gm-0089-0000-c74614a0&tw=3
東二局 2巡

**Comment by Equim-chan** [comment]
Should be fixed in d844ef2 now.

**Comment by nyantlet** [comment]
Thanks for fast feedback! 👍
