### ISSUE TITLE
Failed to download certain mahjong soul log.

### ISSUE THREAD

**Issue by celie1** [Equim-chan/akochan-reviewer#16]
I been using akochan reviewer for quite some time now, and recently I noticed it failed to get certain game log while other log replay is working perfectly fine.

Example:
> Error: failed to download mahjong soul log 210426-42300644-9361-4b8f-a98e-e31293ae006c_a86463819
> 
> Caused by:
>     get mahjong soul log: 500 Internal Server Error
> 

https://game.maj-soul.com/1/?paipu=210426-42300644-9361-4b8f-a98e-e31293ae006c_a86463819

Thank you for your time.

**Comment by Equim-chan** [comment]
It should be fixed now.

**Comment by Orangeniuz** [comment]
Hi there, I am also facing the exact same error as OP.

This is my input from Powershell Windows:

.\akochan-reviewer.exe --lang en --mjsoul-id 210524-32771161-a7c2-4d1f-bf35-c32986ed6_a823825451 -a 2 -o report.hmtl

Am I doing something wrong here? This is my Mahjong Soul Game Log: https://mahjongsoul.game.yo-star.com/?paipu=210524-32771161-a7c2-4d1f-bf35-c32986ed6fd8_a823825451
