### ISSUE TITLE
Points distribution presets for MajSoul

### ISSUE THREAD

**Issue by emerald000** [Equim-chan/akochan-reviewer#18]
While you can currently import a MajSoul game, the point distribution presets only has Tenhou options. It would be nice to have the option to choose MajSoul presets or at the very least to manually enter the point distribution.

**Comment by Equim-chan** [comment]
There is one problem, mjsoul is not using a complete placement score system like tenhou. In tenhou the pt is fixed and completely mapped to the final placement, but mjsoul counts the uma into the pt.

**Comment by emerald000** [comment]
I was not aware the system was different on tenhou. I am assuming akochan cannot handle the uma?

**Comment by Equim-chan** [comment]
Yes, akochan is working on a complete placement model, the results are all placement EVs, nothing else. The pts are simply weights applied to placements.
