### ISSUE TITLE
About 四槓散了

### ISSUE THREAD

**Issue by HellcatTenhou** [Equim-chan/akochan-reviewer#19]
Hello Equim chan,
I occasionally found that akochan could not handle 四槓散了流局 properly.
I was using cmd 
akochan-reviewer --pt 60,15,0,-90 -n 0.02 "https://tenhou.net/0/?log=2021052820gm-0089-0000-ef9e065c&tw=3"
where the address is  https://tenhou.net/0/?log=2021052820gm-0089-0000-ef9e065c&tw=3
四槓散了 occured at 東４局１本場

And Akochan printed that
Error: failed to review log

Caused by:
    0: invalid state in event
    1: unexpected event: Ryukyoku { deltas: Some([0, 0, 0, 0]) }

**Comment by Equim-chan** [comment]
fixed in ab83185
