### ISSUE TITLE
Enhancement: Display kyoku summary in the table of contents

### ISSUE THREAD

**Issue by yuarasino** [Equim-chan/akochan-reviewer#2]
## Description
In order to easily find kyoku user want to see, display the station summary in the table of contents.
Like the official Tenho app.

## Future Image
<img width="823" alt="feature image" src="https://user-images.githubusercontent.com/37145593/76310579-64cdee00-6312-11ea-8d27-8a08d230e2c5.png">

**Comment by Equim-chan** [comment]
What about 流局 and double ロン?

**Comment by yuarasino** [comment]
What about this?

Double ロン
ロン: 自家 8000 ロン: 対面 8000

Normal 流局
流局

"九種九牌" 流局
流局: 九種九牌
The same applies to 四風連打, 三家和, and 四開槓

The official app shows the detailed reason for 流局, but it may not be necessary.

**Comment by Equim-chan** [comment]
I think this can be implemented, but note that it will use overall 収支 instead of 素点. (i.e. 積み棒 and 供託 included). Will it be acceptable?

I haven't parsed types of 流局 from Tenhou log, because akochan doesn't require it. So it might just display "流局".

**Comment by yuarasino** [comment]
> 収支 instead of 素点. (i.e. 積み棒 and 供託 included)

> just display "流局"

I think there is no problem.

**Comment by Equim-chan** [comment]
Could you help me with the HTML part? I will tell you the format of data in template.
