### ISSUE TITLE
Error in reading majsoul log.

### ISSUE THREAD

**Issue by JockeyWang** [Equim-chan/akochan-reviewer#22]
雀魂7月28日更新后，现在读取牌谱会失败。
7月28日雀魂アップデート後、現在読み方エラー発生します。
Now reading Majsoul log leads error after Majsoul updated on 28th July.

**Comment by Equim-chan** [comment]
I am aware of this issue and trying to fix it now.

**Comment by Equim-chan** [comment]
It should be fixed now.

**Comment by DailyPS** [comment]
@Equim-chan Can I ask how did you fix the issue? There is same issue where mahjongsoul paifu is used.

**Comment by Equim-chan** [comment]
@DailyPS https://github.com/Equim-chan/tensoul/compare/b69409ea6b4d7f3344f84c2eb299c05ecf12b6bc...d5ffa93a62e8087e2969480680bf1d25a7c0b591
