### ISSUE TITLE
Error: failed to download mahjong soul log

### ISSUE THREAD

**Issue by rxyil46** [Equim-chan/akochan-reviewer#24]
I came across the problem to get the game log. Also, I can get access to  access https://tensoul.herokuapp.com/ normally. Would you be so kind to help me find a solution to this problem.

> Error: failed to download mahjong soul log https://game.maj-soul.com/1/?paipu=210816-2576a4ac-3c87-472b-bcf0-2d7371a6b3a5_a415362495
> Caused by:
>     get mahjong soul log: 500 Connection Failed

Thank you for your time.

**Comment by Equim-chan** [comment]
Are you using a proxy? Did you set `https_proxy`?

**Comment by rxyil46** [comment]
Yes, I am using V2rayN and setting global proxy. It shown "accepted //tensoul.herokuapp.com:443 [proxy]", but when running cmd, I didn't see the log about this domain.

**Comment by Equim-chan** [comment]
That means you didn't set `http_proxy` and `https_proxy` env. The reviewer will honor this env setting once you set it.

In cmd it should be `set https_proxy=http://xxxxx`

**Comment by rxyil46** [comment]
It works now, thank you for your help.
