### ISSUE TITLE
Enhancement: Display pai images of tehai instead of text

### ISSUE THREAD

**Issue by yuarasino** [Equim-chan/akochan-reviewer#3]
## Description
It is easier to understand that the image of the "tehai" is displayed than the sentence "自家が ？ を引いた時——".

It is difficult because akochan-viewer needs to save the state of the "tehai", but I think it will be a very good change if possible.

## Feature Image
<img width="851" alt="スクリーンショット 2020-03-10 21 09 03" src="https://user-images.githubusercontent.com/37145593/76311898-40bfdc00-6315-11ea-9aed-58defb6ab804.png">

## Implementation method
- Save the state of the "tehai" on akochan-viewer side 
- Replace each tile with image and display

**Comment by Equim-chan** [comment]
This was what I thought at the begining, and even have implemented it partially. I gave up the idea because a Tenhou log viewer can already be embed, and 場況 can be very complex to be described just by tehai and tsumo/dahai. I will re-consider this.

**Comment by Equim-chan** [comment]
Also, fuuros will need to be recorded and displayed correctly as well.

**Comment by Equim-chan** [comment]
I think I can maintain the board state in reviewing, including:
* tehai
* fuuros
* targeted pai from tsumo or dahai

Could you help me in the rendering? I can provide the format of data that will be used in the template.

**Comment by yuarasino** [comment]
Sure! I want to help.

**Comment by Equim-chan** [comment]
The data part is done. You can now pull the latest code, check `templates/report.html` and look up for those `{# TODO: render these #}`. You can also render a review to check the data structure, I have put them in a `<pre>` with json encode.

The template engine is [tera](https://tera.netlify.com/docs/).

## `target_actor`
This the actor id we are reviewing. For example if `target_actor` is 2, then 3 is 下家, 0 is 対面, 1 is 上家, throughout the whole game.

## `kyokus[*].end_status`
It is an array. 

Each of its element has a `type`, which is either `"hora"` or `"ryukyoku"`.

Each element also has a `.deltas`, which is an array of score changes. `.deltas[0]` is the score delta of actor id 0.

For hora, there is an `actor` and a `target`. `actor` is who 和了, `target` is who 放铳. When `target == actor`, it means ツモ. If there are multiple ロン, each element represents a single ロン.

### Example:
#### ツモ
```json
[
  {
    "actor": 0,
    "deltas": [
      4300,
      -1100,
      -2100,
      -1100,
    ],
    "target": 0,
    "type": "hora"
  }
]
```

#### Double ロン
```json
[
  {
    "actor": 3,
    "deltas": [
      0,
      0,
      -7700,
      7700
    ],
    "target": 2,
    "type": "hora"
  },
  {
    "actor": 0,
    "deltas": [
      3900,
      0,
      -3900,
      0
    ],
    "target": 2,
    "type": "hora"
  }
]

```

#### 流局
```json
[
  {
    "deltas": [
      -1500,
      -1500,
      1500,
      1500
    ],
    "type": "ryukyoku"
  }
]

```

## `kyokus[*].entries[*].state`
This is the state of 自家.

If pai is from tsumo (何切る), the `tehai` will have it as the last element. Except the last pai, all other pais are already sorted. 

If pai is from other's dahai (何鳴き), the `tehai` won't have the extra last element.

In each element of the `fuuros` field, there is a `type` field indicating which kind this naki is.

* For "chi", "pon", "daiminkan", there are `target` field describing where the pai is from, and `pai` field describing the naki'd pai.
* For "kakan", there is no `target`, only `pai`.
* For "ankan", there is no `target` or `pai`.

All elements in `fuuros` have `consumed` field, which describes the pais taken from tehai to make the naki.
* For "chi", "pon", it must have and only have 2 elements.
* For "daiminkan", "kakan", it must have and only have 3 elements.
* For "ankan", it must have and only have 3 elements.

You can check `templates/macros.html` for how to render a pai. Note the spaces between pais; in tehai display we don't need them. Also we need to rotate the svg to show fuuros correctly.

### Example
```json
{
  "fuuros": [
    {
      "consumed": [
        "9m",
        "9m"
      ],
      "pai": "9m",
      "target": 1,
      "type": "pon"
    }
  ],
  "tehai": [
    "2m",
    "4m",
    "8m",
    "2p",
    "4p",
    "8p",
    "1s",
    "3s",
    "3s",
    "5s",
    "8s",
    "S",
    "P",
    "2p"
  ]
}

```


Use the following to render 牌背 (used in ankan):

```html
  <svg class="tile">
    <use class="back" xlink:href="#tile"></use>
  </svg>
```

**Comment by yuarasino** [comment]
Thanks for the quick implementation!
I start working.

**Comment by Equim-chan** [comment]
Some changes are made here:

~~For "kakan", there is no `target`, only `pai`.~~

Now "kakan" has `target`, which indicates the target of previous pon.

Also, you need to pull the latest code as I edited the templates a little.

**Comment by yuarasino** [comment]
Next I will work on this issue.

**Comment by yuarasino** [comment]
When type is "daiminkan", the fuuro order was changed.
I cannot fix this in template.

For example, the position of "1s" changes.

<img width="869" alt="スクリーンショット 2020-03-19 16 42 35" src="https://user-images.githubusercontent.com/37145593/77043458-ebfd1f00-6a00-11ea-8df8-e1ee4a31f727.png">

**Comment by yuarasino** [comment]
Is this OK for drawn tile and discard tile?

## when 「自家が を引いた時---」
Display the last tile, "ツモ"
<img width="815" alt="スクリーンショット 2020-03-19 0 58 45" src="https://user-images.githubusercontent.com/37145593/77044381-ad686400-6a02-11ea-8e83-a10867f10dd8.png">

## when 「下家が を切った時---」
Display the last tile, "下家"
The same applies to 上家 and 対面

<img width="853" alt="スクリーンショット 2020-03-19 4 49 08" src="https://user-images.githubusercontent.com/37145593/77044236-667a6e80-6a02-11ea-9dc5-dde0909bae05.png">

**Comment by Equim-chan** [comment]
> When type is "kakan", the fuuro order was changed.

Thank you for pointing it out, I will fix it.

> when 「自家が を引いた時---」
I think if you can render the tehai, the text description can be removed now.

> when 「下家が を切った時---」
Maybe it is better to use "下家打" than "下家"?

**Comment by yuarasino** [comment]
> I think if you can render the tehai, the text description can be removed now.

> Maybe it is better to use "下家打" than "下家"?

I fixed.

<img width="796" alt="スクリーンショット 2020-03-19 18 34 45" src="https://user-images.githubusercontent.com/37145593/77052681-8b75de00-6a10-11ea-9bcb-ac7c927d349d.png">
