### ISSUE TITLE
Strange final decision and place calculation

### ISSUE THREAD

**Issue by Enzegeitor** [Equim-chan/akochan-reviewer#41]
./akochan-reviewer.exe -e --lang en "http://tenhou.net/0/?log=2021121000gm-0029-0000-43854cc9&tw=3&tw=3"

![1](https://user-images.githubusercontent.com/95875652/145461750-db23ff51-e1d5-42a5-bbb6-629b99866dab.jpg)
Akochan recommends skipping the victory.
Is this a bug or a feature?

**Comment by Equim-chan** [comment]
It is an known issue, because your current point is too high, resulting in some numeral instability.
