### ISSUE TITLE
failed to read from akochan: unexpected EOF

### ISSUE THREAD

**Issue by movingduck** [Equim-chan/akochan-reviewer#43]
I run akochan-reviewer in Ubuntu and got this error:
```
system.exe: error while loading shared libraries: libai.so: cannot open shared object file: No such file or directory
Error: failed to review log

Caused by:
    failed to read from akochan: unexpected EOF
```

**Comment by Equim-chan** [comment]
You either can set `LD_LIBRARY_PATH` at run time or set `-Wl,-rpath` at compile time to resolve this.

**Comment by movingduck** [comment]
Thanks for the response. I am not quite understand how it works. Can you explain more?

**Comment by movingduck** [comment]
I have figured it out. Thanks.
