### ISSUE TITLE
Fail to locate my file

### ISSUE THREAD

**Issue by faketw** [Equim-chan/akochan-reviewer#45]
I am a beginner with computer and very interested in this AI, so I have just gone through the tutor and already built akochan and akochan-reviewer under my home dir.
By the way, my system is macOS 12.2.1 and when I was building akochan using make statement, my terminal gave me a lot of warnings, I don't know if this is relevant.
The problem is when I run '~/akochan-reviewer/target/release/akochan-reviewer -I <file> -a 0' under home dir, this error occurs.
18:16:18.042392 src/main.rs:506	converting to mjai events...
Error: failed to canonicalize tactics_config path "tactics.json"

Caused by:
    No such file or directory (os error 2)
But I can find my "tactics.json file" under ~/akochan-reviewer.
And when I run '~/akochan-reviewer/target/release/akochan-reviewer -I <file> -a 0' under another dir, it will give me another error.
18:43:20.950012 src/main.rs:506	converting to mjai events...
Error: failed to canonicalize akochan_dir path "akochan"

Caused by:
    No such file or directory (os error 2)
Can anyone tell me why this happen and how can I run this AI successfully on my Mac.

**Comment by Equim-chan** [comment]
You need to specify `-d dir_to_akochan`

**Comment by faketw** [comment]
Wow, it works, thank you so much.
