### ISSUE TITLE
Missing turn in replay examination

### ISSUE THREAD

**Issue by Canophia** [Equim-chan/akochan-reviewer#47]
The Majsoul paipu is https://game.maj-soul.com/1/?paipu=220312-b4481a3d-57c0-4d89-b096-d7dd9dd7d837_a19427114

I followed the instruction [here](https://github.com/Equim-chan/akochan-reviewer/blob/master/mjsoul.adoc) and used tempermonkey to download the paipu above. I tried to use akochan-reviewer to analyse it, using the command `.\akochan-reviewer.exe -i .\2022_3_12_Gold_Room_South.json -n 0.1 --pt 110,50,-10,-130 -a 3 -k S1`, but found the 2nd turn was skipped when I pon 7m.

![Image](https://user-images.githubusercontent.com/36223597/158022292-2463600b-c9d0-4603-9354-225f9f09dd71.png)

**Comment by JaySon-Huang** [comment]
It is because your tehai is too far away from tenpai, akochan don't think you should pon the 7m. Even after you pon the 7m, it is "3向聴" 👀
