### ISSUE TITLE
Preparing a list of special situation 牌譜 for development

### ISSUE THREAD

**Issue by yuarasino** [Equim-chan/akochan-reviewer#5]
# Description
If 牌譜 of special situations are listed, development becomes easier.
For example, short 牌譜、Double ロン、暗槓、加槓、大明槓、no akochan review etc...）

There is no need to prepare it immediately, so I want you to share your 牌譜ID somewhere when you find it.

Double ロン 牌譜 was found in [the public 牌譜s in Tenhou site](https://tenhou.net/0/mjloglist.cgi?mjlog_pf4-20_n1)

-  https://tenhou.net/3/?log=2009061908gm-0009-0000-37941efb&tw=3

**Comment by Equim-chan** [comment]
It is already included under `convlog/tests/testdata`. Although they are there originally for testing `convlog` crate, you can use them for testing `akochan-reviewer`, like

```console
$ cargo run -- -i convlog/tests/testdata/double_ron.json -a 1
```

**Comment by yuarasino** [comment]
Thanks for the explanation of the test data and the provision of how to use it!
