### ISSUE TITLE
Add a new horizontal layout for the report

### ISSUE THREAD

**Issue by JaySon-Huang** [Equim-chan/akochan-reviewer#50]
Hi, I am new to mahjong and find akochan-reviewer is useful for learning. Thanks a lot for this project!

However, I found it is a litter hard to check the review result and the tenhou replaying at the same time. There is only limited space if I don't collapse the tenhou replay iframe.

I try to add a horizontal layout to place the tenhou replay to the left and the review result to the right side. Here are my changes https://github.com/JaySon-Huang/akochan-reviewer/tree/hori_style

I am thinking of merging it back to this repo. Would you mind accepting the layout change?

A preview for the report with horizontal layout:
[chankan.json.html.zip](https://github.com/Equim-chan/akochan-reviewer/files/8308615/chankan.json.html.zip)
![image](https://user-images.githubusercontent.com/4865550/159107530-4726c89d-0ad3-407b-8616-2c480803dd8d.png)

**Comment by Equim-chan** [comment]
Thank you for your good work. However, generally I am not quite satisfied with my current design which has to use Tenhou's player. I've always wanted to make it more interactable just like that in NAGA's reviewer, but I've been struggling with my poor designing and front-end skills.

I may still merge this though, yet I think someday I (or somebody else who'd like to help) will redesign the whole thing.

**Comment by JaySon-Huang** [comment]
It's great if the reviewer can have its own interactable UI. Indeed it needs someone who is familiar with front-end.

And it would be great if we can show "好型"/"愚型" like this script when comes to "一向听"
https://greasyfork.org/zh-TW/scripts/435111-%E5%A4%A9%E9%B3%B3%E7%89%8C%E7%90%86%E5%A5%BD%E5%BD%A2%E8%A1%A8%E7%A4%BA/code
