### ISSUE TITLE
Error: failed to canonicalize akochan_dir path "akochan"

### ISSUE THREAD

**Issue by Eurus0209** [Equim-chan/akochan-reviewer#51]
```
% ./akochan-reviewer -a 0 -i 01.json
17:17:12.312590 src/main.rs:506	converting to mjai events...
Error: failed to canonicalize akochan_dir path "akochan"

Caused by:
    No such file or directory (os error 2)
```

**Comment by JaySon-Huang** [comment]
You need to checkout akochan repo and build it before running akochan-reviewer. https://github.com/Equim-chan/akochan-reviewer#build-akochan

If the `akochan` directory is not under the same directory of your binary, you can specify it by using the `--akochan-dir <DIR>`
