### ISSUE TITLE
じゃんたま東風戦の牌譜検討について

### ISSUE THREAD

**Issue by tb158** [Equim-chan/akochan-reviewer#54]
こんにちは。日本語で失礼いたします。

じゃんたまの東風戦の牌譜をローカルでakochanに検討させているのですが、オーラスのpt期待値を見るに南場が残っている想定で検討されているように思いました。

東風戦の想定で検討させることは可能でしょうか？前提からして間違っていたらごめんなさい。

**Comment by Equim-chan** [comment]
> 東風戦の想定で検討させることは可能でしょうか？

It is possible. For akochan, it checks `kyoku_first` at the `start_game` event. If it is `4` than it will be 東風戦.

**Comment by tb158** [comment]
すみません、kyoku_firstというパラメータがあるのでしょうか。

https://github.com/Equim-chan/akochan-reviewer/blob/master/mjsoul.adoc

の手順で使用する牌譜のjsonファイルや、tactic.jsonの中身、それとhttps://github.com/Equim-chan/akochan-reviewerのコマンドを調べてもそのようなパラメータについての記述が見つかりません😣😣😣

牌譜検討の結果生成されたhtmlで"Meta date"を確認したところ、"game length"が"半荘"となっていました。
東風戦ルールを指定するにはどのようにしたら良いのでしょうか？

**Comment by tb158** [comment]
> It is possible. For akochan, it checks kyoku_first at the start_game event. If it is 4 than it will be 東風戦.

When akochan reads a json file of a 東風 game log, does it automatically determine that the log is of a 東風 game?
However, as mentioned above, the log is actually determined to be of a 半荘 game.

An example of the execution log is

>C:\Users\gihos\Downloads\akochan-reviewer-v0.6.0-windows-x86_64>akochan-reviewer.exe -i "2022_3_25_Jade_Room_East (1).json" -a 1 --pt 100,0,0,0 -n 0.05
23:57:46.761114 src\main.rs:507 converting to mjai events...
23:57:46.800744 src\main.rs:603 players: マダムフセイン, shogitb, 88+++, 豚ブラジャー
23:57:46.802088 src\main.rs:604 target: shogitb
23:57:46.803608 src\main.rs:605 review has started, this may take several minutes...
23:57:46.922153 src\review.rs:221       reviewing kyoku=0 honba=0 junme=0 (0.44%)
23:57:49.076000 src\review.rs:221       reviewing kyoku=0 honba=0 junme=1 (0.59%)
…
00:06:12.708755 src\review.rs:221       reviewing kyoku=3 honba=0 junme=18 (99.41%)
00:06:13.432080 src\main.rs:684 rendering output...
00:06:13.911312 src\main.rs:698 done

The value of `kyoku` is 0 instead of 4 at the start_game. Does it have anything to do with kyoku_first?

Thank you for your help and cooperation.

**Comment by Equim-chan** [comment]
Try this:

```
akochan-reviewer.exe --no-review --mjai-out mjai.json -i "2022_3_25_Jade_Room_East (1).json"
```

Then open `mjai.json`, the first line will be a `start_game` event, and you will find `kyoku_first` there. But akochan-reviewer does not accept mjai input yet, it only outputs mjai, I think you could investigate the tenhou/6 log format.

**Comment by tb158** [comment]
Thank you for your reply.
I have investigated and found that if I rewrite 

>"rule": { "disp": "Jade Room East", "aka53": 1, "aka52": 1, "aka51": 1 },

 in the tenhou/6 log to 

>"rule": { "disp": "特東喰赤", "aka53": 1, "aka52": 1, "aka51": 1 },

, it will be recognized as a 東風 game.

I will use akochan a lot!
Thank you for your kind cooperation.
