### ISSUE TITLE
Service unavailable?

### ISSUE THREAD

**Issue by Zeks** [Equim-chan/akochan-reviewer#56]
docker version doesn't work with:

```
Error: failed to download mahjong soul log 220329-ce1da608-fc05-4560-bcfa-ff0185f91f92_a829847388

Caused by:
    get mahjong soul log: 503 Service Unavailable

```

**Comment by Equim-chan** [comment]
See https://github.com/Equim-chan/akochan-reviewer/blob/master/mjsoul.adoc

**Comment by Zeks** [comment]
Thank you! I was able to build a lcoal instance but I ran into two problems that might be helpful to have in the building troubleshooting section:
1) when you run it from target/release you get 
```
15:39:38.155207 src/main.rs:561	converting to mjai events...
Error: failed to canonicalize akochan_dir path "akochan"
```

This is solved by running it from the root directory like ./target/release/akochan-reviewer

2) it fails to find libai which is solved by prepending LD_LIBRARY_PATH to teh command:
```
LD_LIBRARY_PATH=/home/zeks/akochan-reviewer/akochan ./target/release/akochan-reviewer -i logs/logfile.json -a 3

```
