### ISSUE TITLE
What is a proper url to download tenhou logs?

### ISSUE THREAD

**Issue by Zeks** [Equim-chan/akochan-reviewer#58]
Akochan does it somehow, but I can't get it to work locally trying to do this:

`curl "https://tenhou.net/5/mjlog2json.cgi?log=2022041620gm-0009-0000-ff59f844&tw=1&tw=1" -H 'Content-Type: application/json' --data-raw '{  "Referer": "https://tenhou.net/"}' > ~/test.html`

The idea is that I want to be able to save logs and then feed them to akochan later with -i command instead of relying on logs still being available and using akochan's fetcher.

**Comment by Equim-chan** [comment]
`Referer` is a header field, not data.

**Comment by Zeks** [comment]
Okay, it downloaded, but now it says "failed to parse tenhou.net/6 log". The contents do indeed look liem a log file. Anything that  needs to be done to this file
[test.html.zip](https://github.com/Equim-chan/akochan-reviewer/files/8500082/test.html.zip)
?

**Comment by Zeks** [comment]
Mhm, correction: I can download like this: 
`curl "https://tenhou.net/0/log/?2022041620gm-0009-0000-ff59f844" -H 'Referer: https://tenhou.net/'  > ~/test.html`
but not like this:
`curl "https://tenhou.net/5/mjlog2json.cgi?log=2022041620gm-0009-0000-ff59f844&tw=1&tw=1" -H 'Referer: https://tenhou.net/'  > ~/test.html`


the latter returns an empty page
