### ISSUE TITLE
akochan can't identify three colors as base rong.

### ISSUE THREAD

**Issue by RuoClover** [Equim-chan/akochan-reviewer#61]
![bug](https://user-images.githubusercontent.com/42854588/167291334-c1fac664-fc0a-476d-bc7f-69fc2936f6f3.png)

**Comment by Equim-chan** [comment]
You should post this in [critter-mj/akochan](https://github.com/critter-mj/akochan) instead.

**Comment by RuoClover** [comment]
ok
