### ISSUE TITLE
akochan demands chii on another players kan.

### ISSUE THREAD

**Issue by anytime1235** [Equim-chan/akochan-reviewer#63]
![image](https://user-images.githubusercontent.com/106418715/170808780-46e2648a-8e59-4ae5-81ef-d168218c6ca8.png)

Akochan calls on 7 pin, which is impossible because left player used it for kan not for discard.

**Comment by Equim-chan** [comment]
You should post this in [critter-mj/akochan](https://github.com/critter-mj/akochan)

**Comment by anytime1235** [comment]
Thanks for notifying. I didn't know
