### ISSUE TITLE
报了个错，咋解决

### ISSUE THREAD

**Issue by Berial** [Equim-chan/akochan-reviewer#64]
$ .\akochan-reviewer.exe "http://tenhou.net/0/?log=2022052822gm-0009-0000-9f823350&tw=1&tw=1"
22:47:16.623991 src\main.rs:506 converting to mjai events...
22:47:16.625292 src\main.rs:600 players: ドラゴン5, 椎名まゆり, NoName, まのさきゆゆ
22:47:16.625551 src\main.rs:601 target: 椎名まゆり
22:47:16.625808 src\main.rs:602 review has started, this may take several minutes...
22:47:16.630096 src\review.rs:219       reviewing kyoku=0 honba=0 junme=0 (0.25%)
Assertion failed: tehai_bit.count_hai(hai-5) >= tehai_state.get_aka_in_side(hai/10 - 1), file tehai_ana.cpp, line 263
Error: failed to review log

Caused by:
    failed to read from akochan: unexpected EOF

**Comment by Equim-chan** [comment]
尝试第一个方法 https://github.com/Equim-chan/akochan-reviewer#troubleshooting

**Comment by Berial** [comment]
多谢，能用了，这个点还没睡觉啊
