### ISSUE TITLE
Unspecified in-file doesn't open stdin

### ISSUE THREAD

**Issue by Euophrys** [Equim-chan/akochan-reviewer#8]
Running this command:
`docker run --rm akochan-reviewer:latest --no-open -i - -a 1 -o - > report.html`

Results in this error:
```
src/main.rs:334 parsing tenhou log...
Error: failed to parse tenhou log

Caused by:
    EOF while parsing a value at line 1 column 0
```

According to the readme, it should read from stdin in this case.

**Comment by Equim-chan** [comment]
Try using `docker run -i ...` 

> --interactive , -i    Keep STDIN open even if not attached

**Comment by Euophrys** [comment]
That still passes through for me, although it doesn't hit the error:
```
docker run -i --rm akochan-reviewer:latest --no-open -i - -a 1 -o - > report.html
src/main.rs:334 parsing tenhou log...
```

**Comment by Equim-chan** [comment]
This is correct, it is now waiting for stdin for some input.

The line `parsing tenhou log...` is actually printed before reading anything.
